name: "DeploymentEnv Status"
description: "Pushes a slack message"
author: "XGManuelJager"
branding:
  icon: arrow-up
  color: gray-dark
inputs:
  webhook_url:
    description: "Slack webhook url to send messages to"
    required: true
  env:
    description: "environment of the deployment"
    required: true
  env_url:
    description: "url of the deployment"
    required: false
  state:
    description: "Workflow state. Enum: success | failure | cancelled"
    required: true
  dashboard_url:
    description: "url of the dashboard"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
