name: "Validate"
on: [push]

jobs:
  deploy:
    name: Create test deployment

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: ./
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          environment_url: http://my-app-url.com
          environment: production
          deployment_id: 1

      - name: Update deployment status
        uses: ./
        with:
          token: "${{ github.token }}"
          environment_url: http://my-app-url.com
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
