name: "Validate"
on: [push]

jobs:
  deploy:
    name: Create test deployment

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Update deployment status
        uses: ./
        with:
          webhook_url: "${{ secrets.SLACK_DEPLOYMENT_WEBHOOK }}"
          env: production
          env_url: http://my-app-url.com
          failure: "${{ failure() }}"
          success: "${{ success() }}"