name: "Validate"
on: [push]

jobs:
  deploy:
    name: Create test deployment

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Update deployment status
        uses: ./
        if: success()
        with:
          webhook_url: ${{ secrets.SLACK_DEPLOYMENT_WEBHOOK }}
          env: production
          env_url: http://my-app-url.com
          state: success

      - name: Update deployment status
        uses: ./
        if: failure()
        with:
          webhook_url: ${{ secrets.SLACK_DEPLOYMENT_WEBHOOK }}
          env: production
          env_url: http://my-app-url.com
          state: failure